// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using com.jobsite.chat.Repository.Persistence;

#nullable disable

namespace com.jobsite.chat.Repository.Persistence.Migrations.Chat
{
    [DbContext(typeof(ChatDbContext))]
    partial class ChatDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("com.jobsite.chat.Domain.Entities.ChatMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("TEXT");

                    b.Property<long>("SentAtUtc")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RoomId", "SentAtUtc");

                    b.ToTable("Messages", (string)null);
                });

            modelBuilder.Entity("com.jobsite.chat.Domain.Entities.ChatRoom", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Rooms", (string)null);
                });

            modelBuilder.Entity("com.jobsite.chat.Domain.Entities.ChatMessage", b =>
                {
                    b.OwnsOne("com.jobsite.chat.Domain.ValueObjects.MessageAuthor", "Author", b1 =>
                        {
                            b1.Property<Guid>("ChatMessageId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("DisplayName")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("TEXT")
                                .HasColumnName("AuthorDisplayName");

                            b1.Property<string>("UserId")
                                .HasMaxLength(450)
                                .HasColumnType("TEXT")
                                .HasColumnName("AuthorUserId");

                            b1.HasKey("ChatMessageId");

                            b1.ToTable("Messages");

                            b1.WithOwner()
                                .HasForeignKey("ChatMessageId");
                        });

                    b.Navigation("Author")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
